version: "3.5"

services:
  prometheus:
    # container_name: prometheus
    image: bitnami/prometheus:2.33.1
    restart: unless-stopped
    tty: true
    volumes:
      # - /data/zcc-test-2/prometheus/data:/opt/bitnami/prometheus/data # all metrics are gauge, no need to store it.
      - /home/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml

