# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

  external_labels:
    monitor: polygon-edge-zcc-test

# rule_files:
#   - "first.rules"
#   - "my/*.rules"

# remote_write:
#   - url: http://remote1/push
#     name: drop_expensive
#     write_relabel_configs:
#       - source_labels: [__name__]
#         regex: expensive.*
#         action: drop
#     oauth2:
#       client_id: "123"
#       client_secret: "456"
#       token_url: "http://remote1/auth"
#       tls_config:
#         cert_file: valid_cert_file
#         key_file: valid_key_file

#   - url: http://remote2/push
#     name: rw_tls
#     tls_config:
#       cert_file: valid_cert_file
#       key_file: valid_key_file
#     headers:
#       name: value

# remote_read:
#   - url: http://remote1/read
#     read_recent: true
#     name: default
#   - url: http://remote3/read
#     read_recent: false
#     name: read_special
#     required_matchers:
#       job: special
#     tls_config:
#       cert_file: valid_cert_file
#       key_file: valid_key_file

scrape_configs:
  - job_name: polygon-edge-zcc-test-cluster

    honor_labels: true
    # scrape_interval is defined by the configured global (15s).
    # scrape_timeout is defined by the global default (10s).

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    # file_sd_configs:
    #   - files:
    #       - foo/*.slow.json
    #       - foo/*.slow.yml
    #       - single/file.yml
    #     refresh_interval: 10m
    #   - files:
    #       - bar/*.yaml

    #params:
    #  "match[]":
    #    - '{__name__=~"^consensus_.*"}'
    #    - '{__name__=~"^network_.*"}'
    #    - '{__name__=~"^txpool_.*"}'

    static_configs:
      - targets: 
        - "172.51.0.11:9090"
        # labels:
        #   my: label
        #   your: label

    # relabel_configs:
    #   - source_labels: [job, __meta_dns_name]
    #     regex: (.*)some-[regex]
    #     target_label: job
    #     replacement: foo-${1}
    #     # action defaults to 'replace'
    #   - source_labels: [abc]
    #     target_label: cde
    #   - replacement: static
    #     target_label: abc
    #   - regex:
    #     replacement: static
    #     target_label: abc

    # authorization:
    #   credentials_file: valid_token_file

#   - job_name: service-x

#     basic_auth:
#       username: admin_name
#       password: "multiline\nmysecret\ntest"

#     scrape_interval: 50s
#     scrape_timeout: 5s

#     body_size_limit: 10MB
#     sample_limit: 1000

#     metrics_path: /my_path
#     scheme: https

#     dns_sd_configs:
#       - refresh_interval: 15s
#         names:
#           - first.dns.address.domain.com
#           - second.dns.address.domain.com
#       - names:
#           - first.dns.address.domain.com

#     relabel_configs:
#       - source_labels: [job]
#         regex: (.*)some-[regex]
#         action: drop
#       - source_labels: [__address__]
#         modulus: 8
#         target_label: __tmp_hash
#         action: hashmod
#       - source_labels: [__tmp_hash]
#         regex: 1
#         action: keep
#       - action: labelmap
#         regex: 1
#       - action: labeldrop
#         regex: d
#       - action: labelkeep
#         regex: k

#     metric_relabel_configs:
#       - source_labels: [__name__]
#         regex: expensive_metric.*
#         action: drop

# alerting:
#   alertmanagers:
#     - scheme: https
#       static_configs:
#         - targets:
#             - "1.2.3.4:9093"
