version: "3.5"

# networks:
#   mynet2:
#     ipam:
#       config:
#         - subnet: 172.51.0.0/16
networks:
  mynet:
    external:
       name: zcc-test-2_mynet2


services:
  prometheus:
    # container_name: prometheus
    image: bitnami/prometheus:2.33.1
    restart: unless-stopped
    tty: true
    volumes:
      # - /data/zcc-test-2/prometheus/data:/opt/bitnami/prometheus/data # all metrics are gauge, no need to store it.
      - /data/zcc-test-2/prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    networks:
      mynet:
        ipv4_address: 172.51.0.110

