---
# tasks file for generate genesis.json

- name: Stop service 
  become: true
  ansible.builtin.systemd:
    name: jury
    state: stopped

- name: Remove jury-install directory
  file:
    path: "{{ ansible_env.HOME }}/jury-install"
    state: absent

- name: Remove data directory
  become: true
  file:
    path: "{{ INIT_DATA_DIR }}"
    state: absent

- name: Remove /usr/bin/jury
  become: true
  file:
    path: /usr/bin/jury
    state: absent

- name: Remove jury.service
  become: true
  file:
    path: /etc/systemd/system/jury.service
    state: absent
