---
# tasks file for config-secrets

- name: Copy jury to remote
  copy:
    src: "{{playbook_dir}}/../manifests/jury"
    dest: "{{ ansible_env.HOME }}/jury-install/"
    mode: 0755

- name: Remove symlink for jury
  become: true
  file:
    path: "/usr/bin/jury"
    state: absent

- name: Creating symlink for jury
  file:
    src: "{{ ansible_env.HOME }}/jury-install/jury"
    dest: "/usr/bin/jury"
    state: link
  become: true

- name: Remove old secrets directory
  become: true
  file:
    path: "{{ INIT_DATA_DIR }}"
    state: absent

- name: Create secrets directory
  become: true
  file:
    path: "{{ INIT_DATA_DIR }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Init Secrets
  shell: /usr/bin/jury secrets init --data-dir "{{ INIT_DATA_DIR }}" > "{{ ansible_env.HOME }}/jury-install/init_secrets_output-{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- name: Copy get-secrets-nodeinfo.sh to remote
  copy:
    src: "{{playbook_dir}}/../manifests/get-secrets-nodeinfo.sh"
    dest: "{{ ansible_env.HOME }}/jury-install/"
    mode: 0755

- name: Execute get-secrets-nodeinfo.sh
  command: "bash get-secrets-nodeinfo.sh {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  args:
    chdir: "{{ ansible_env.HOME }}/jury-install/"

- name: Copy get-node-address.sh to remote
  copy:
    src: "{{playbook_dir}}/../manifests/get-node-address.sh"
    dest: "{{ ansible_env.HOME }}/jury-install/"
    mode: 0755

- name: Execute get-node-address.sh
  command: "bash get-node-address.sh {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  args:
    chdir: "{{ ansible_env.HOME }}/jury-install/"

- local_action: file path="{{ playbook_dir }}/../manifests/secrets_nodeinfo_output" state=absent

- name: Feth secrets_nodeinfo_output from remote to local.
  ansible.builtin.fetch:
    src: "{{ ansible_env.HOME }}/jury-install/secrets_nodeinfo_output-{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    dest: "{{ playbook_dir }}/../manifests/secrets_nodeinfo_output/"
    flat: yes

- name: Feth node_address_output from remote to local.
  ansible.builtin.fetch:
    src: "{{ ansible_env.HOME }}/jury-install/node_address_output-{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    dest: "{{ playbook_dir }}/../manifests/secrets_nodeinfo_output/"
    flat: yes
